spring.datasource.url=jdbc:mysql://localhost:3306/warehouse
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=vhgx2Mf6vw1S9VpgjmUrbYc8u1vcXzT69ttlhWjHVo2WkZffOg6hM7dD/4BDI4Qv
jwt.expiration=86400000
